name: Docker Build and Push

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - mvc.mssqllistener
          - mvc.mysqlListener
          - mvc.oraclelistener
          - mvc.postgresqllistener
        dockerfile:
          - mvc.mssqllistener.dockerfile
          - mvc.mysqllistener.dockerfile
          - mvc.oraclelistener.dockerfile
          - mvc.postgresqllistener.dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.project }}:latest ./${{ matrix.project }}

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.project }}:latest
