name: Docker Build and Push

on:
  push:
    branches:
      - 'release'     

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - MVC.MSSQLListener
          - MVC.MySQLListener
          - MVC.OracleListener
          - MVC.PostgreSQLListener
        dockerfile:
          - mvc.mssqllistener.dockerfile
          - mvc.mysqllistener.dockerfile
          - mvc.oraclelistener.dockerfile
          - mvc.postgresqllistener.dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Convert project name to lowercase
        id: lowercase
        run: echo "lowercase_project_name=$(echo ${{ matrix.project }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/"${{ env.lowercase_project_name }}":latest -f ./${{ matrix.dockerfile }} .

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.lowercase_project_name }}:latest
